### ISSUE TITLE
Scoped Signature Verification Policy

### ISSUE THREAD

**Issue by iamsamirzon** [notaryproject/roadmap#18]
**Summary** The standard should allow to scope the signature verification to a narrower namespace of registry/repo
**Intended Outcome**
The specfication PR is merged
**Additional context**
Should support mixed images usecase - signed and unsigned images; and namespaces like : Registry/Repositry, or just Registry only; This reduces blast radius; Allows workloads to be configured to pull from different registries and only expect specific keys/certificates from specific registries;

**Comment by priteshbandi** [comment]
https://github.com/notaryproject/notaryproject/pull/119

**Comment by iamsamirzon** [comment]
This was addressed as part of https://github.com/notaryproject/notaryproject/pull/119
