### ISSUE TITLE
Signature Verification process

### ISSUE THREAD

**Issue by iamsamirzon** [notaryproject/roadmap#19]
**Summary** Cover the Trust Store and Trust Policy usage
**Intended Outcome**
The specfication PR is merged
**Additional context**
This is in baseline implementation for alpha release, but need to ensure specfication is well defined. Should support verifying any registry artifact like SBOM and vulnerebility scan results

**Comment by iamsamirzon** [comment]
Question : Should Notation allow use of standard trust stores available on operating systems

**Comment by priteshbandi** [comment]
https://github.com/notaryproject/notaryproject/pull/122

Question : Should Notation allow use of standard trust stores available on operating systems
> IMO the better approach would be to have list of publically trusted roots if required we can add this support but user will need to explicitly call it out.

**Comment by iamsamirzon** [comment]
This related PR for public signature is part of the signature verification process. https://github.com/notaryproject/notaryproject/pull/132

**Comment by iamsamirzon** [comment]
@SteveLasker  - This is ready to be closed now that https://github.com/notaryproject/notaryproject/pull/122 is merged.
