### ISSUE TITLE
Signature Payload Format

### ISSUE THREAD

**Issue by iamsamirzon** [notaryproject/roadmap#2]
**Summary**
The payload format for the finalized signature
**Intended Outcome**
**Additional context** 
Descriptor+Annotation+Metadata; not fully agreed yet; the signature format PR should have some details on it as part of the alpha-1 release.

**Comment by SteveLasker** [comment]
Adding 
- https://github.com/notaryproject/notaryproject/issues/117 
- https://github.com/notaryproject/notaryproject/issues/123

for reference in completing the format.

**Comment by iamsamirzon** [comment]
@dtzar - This can be closed in our next NV2 meeting for RC-1 as well. The work was done as part of PR https://github.com/notaryproject/notaryproject/pull/158

**Comment by dtzar** [comment]
The JWS format is complete.  The COSE format is tracked in separate issues as listed above.  Closing on call with Samir 7/28
