### ISSUE TITLE
Matching signatures to trust policy

### ISSUE THREAD

**Issue by iamsamirzon** [notaryproject/roadmap#20]
**Summary** Define the specification for signatures matching to the trust policy
**Intended Outcome**
The specification PR is merged
**Additional context**
This will

**Comment by priteshbandi** [comment]
PR: notaryproject/notaryproject#122

**Comment by priteshbandi** [comment]
Trust Anchor support: https://hackmd.io/iPBEpv-nSB2LZjTSfD-FBA

**Comment by iamsamirzon** [comment]
@SteveLasker - This is ready to be closed because https://github.com/notaryproject/notaryproject/pull/122 is now merged
