### ISSUE TITLE
Signing plugin interface API Spec

### ISSUE THREAD

**Issue by iamsamirzon** [notaryproject/roadmap#26]
**Summary**
**Intended Outcome**
The APIs for setting up the signing provider are clearly defined and documented
**Additional context**
This is in baseline implementation for alpha release, but need to ensure specification is well defined
Related to https://github.com/notaryproject/notaryproject/pull/124 

Details for this specification captured in  https://hackmd.io/jhYbA4aNRFW7nmp7gPTIBA?view

**Comment by SteveLasker** [comment]
@gokarnm, can we convert this to a PR and see if we can get closure? I think we have enough to complete the Azure keyvault plug-in and hopefully implement a [hashicorp plug-in](https://github.com/notaryproject/roadmap/issues/54) as well.

**Comment by iamsamirzon** [comment]
Waiting on this PR getting merged - https://github.com/notaryproject/notaryproject/pull/124 before we can close this roadmap item

**Comment by iamsamirzon** [comment]
https://github.com/notaryproject/notaryproject/commits/main/specs/plugin-extensibility.md

**Comment by dtzar** [comment]
LGTM to close as well.
