### ISSUE TITLE
Verification Plugin interface API Spec

### ISSUE THREAD

**Issue by iamsamirzon** [notaryproject/roadmap#27]
**Summary**
**Intended Outcome**
The APIs for extensibility (such as for revocation checks) are clearly defined and documented
**Additional context**
This is in baseline implementation for alpha release, but need to ensure specification is well definedE.g. Fetch revocation status, or public key

**Comment by iamsamirzon** [comment]
Renamed the Issue to make it symmetrical to the corresponding signing item https://github.com/notaryproject/roadmap/issues/26

**Comment by gokarnm** [comment]
Addressed in this [PR](https://github.com/notaryproject/notaryproject/pull/165).
