### ISSUE TITLE
Verification API Implementation

### ISSUE THREAD

**Issue by iamsamirzon** [notaryproject/roadmap#29]
**Summary**
**Intended Outcome**
The APIs are implemented in GO programming language
**Additional context**
Will be revised based on spec updates in next release; The first alpha release will have a version of it.; This is dependent on the "signature format" to be completed in alpha-3;

**Comment by iamsamirzon** [comment]
@dtzar   -There are three interlinked items here. We are close to completion on this roadmap item.
1. Basic verification in progress -https://github.com/notaryproject/notation-core-go/pull/7 
2. Verification extensibility - ongoing discussions in the community 
3. Trust store and trust policy - being tracked seprately.

**Comment by dtzar** [comment]
Closing with Samir on call 7/28
