### ISSUE TITLE
Signature Manifest Format

### ISSUE THREAD

**Issue by iamsamirzon** [notaryproject/roadmap#3]
**Summary**
Signature Manifest format for the finalized signature  
**Intended Outcome**
**Additional context ** 
e.g. What annotations will be there;

**Comment by iamsamirzon** [comment]
@dtzar  - This one can also be closed for alpha-3/RC-1 milestone. The work is completed as part of PR https://github.com/notaryproject/notaryproject/pull/158

**Comment by dtzar** [comment]
LGTM to close as well.
