### ISSUE TITLE
Signing plugin integration - Remote Key Store Signing API Implementation

### ISSUE THREAD

**Issue by iamsamirzon** [notaryproject/roadmap#32]
**Summary**
**Intended Outcome**
The APIs are implemented in GO programming language
**Additional context**
Interface to allow customers to hook up their remote or local HSM based key stores (KMS, YubiKeys)

This is related to the spec which is being tracked via https://github.com/notaryproject/roadmap/issues/26

**Comment by gokarnm** [comment]
Signing plugin spec defines `signature-generator` and `envelope-generature` interfaces. `signature-generator` implementation is complete, and `envelope-generature` is pending.

**Comment by dtzar** [comment]
@qmuntal has already implemented 2/3 of the spec with https://github.com/notaryproject/notation/pull/168

**Comment by iamsamirzon** [comment]
@dtzar - I believe we are ready to close this roadmap item.
The "envelope-generator" code is completed.  
- https://github.com/notaryproject/notation-go/blob/main/signature/plugin.go#L161

Here is the code implementation for the signing plugin.
- https://github.com/notaryproject/notation-go/tree/main/plugin
