### ISSUE TITLE
Signing plugin integration - Signing Service API Implementation

### ISSUE THREAD

**Issue by iamsamirzon** [notaryproject/roadmap#33]
**Summary**
**Intended Outcome**
The APIs are implemented in GO programming language
**Additional context**
Interface to allow customers to hook up their cloud based signing services

**Comment by iamsamirzon** [comment]
@gokarnm - Is this covered as part of the Signing Plugin implementation?

**Comment by priteshbandi** [comment]
This has already been completed as part of https://github.com/notaryproject/notaryproject/blob/main/specs/plugin-extensibility.md

**Comment by vaninrao10** [comment]
This has already been completed as part of https://github.com/notaryproject/notaryproject/blob/main/specs/plugin-extensibility.md
