### ISSUE TITLE
CLI command specification

### ISSUE THREAD

**Issue by iamsamirzon** [notaryproject/roadmap#36]
**Summary**
User/Implementers Guide
**Intended Outcome** 
There should be a specification to help implementers understand the architecture of the CLI engine for continuing to maintain and extend it. 
**Additional context**
Linked Issue : https://github.com/notaryproject/notation/issues/88

**Comment by dtzar** [comment]
https://github.com/notaryproject/notation/pull/171/files

**Comment by dtzar** [comment]
@iamsamirzon The problem with this issue as well as 41 is that is too generic and doesn't demonstrate specific user value.  notation has many sub-commands and we know many of them are not necessarily in scope for improvement/enhancement in even RC-1. 

My suggestion would be to close issues like this out and just migrate over the [user stories we have in the notation repository](https://github.com/notaryproject/notation/issues?q=is%3Aopen+is%3Aissue+label%3A%22User+Story%22) to track.

**Comment by iamsamirzon** [comment]
@dtzar - I am ok with closing this one as we discussed in the 8/1/2022 Notary V2 meeting. As for https://github.com/notaryproject/roadmap/issues/41 , I think we can repurpose it and convert this into a user story/CLI command specification and implementation for the "Notation verify".
