### ISSUE TITLE
CLI Cmds for Configuration

### ISSUE THREAD

**Issue by iamsamirzon** [notaryproject/roadmap#37]
**Summary** 
CLI cmmands for configuration of Notation CLI Client
**Intended Outcome**
The specfication PR is merged
**Additional context**
Includes configuring signing provider, trust store and trust policy

**Comment by iamsamirzon** [comment]
Once the trust policy and trust stores are defined as part of (https://github.com/notaryproject/notaryproject/pull/122), we will revisit this roadmap item and then decide if we need to define policies and stores via CLI commands or leave them as JSON objects; This affects usability.

**Comment by iamsamirzon** [comment]
@iamsamirzon  - assign this to < qmuntal> . Work has started on this already.

**Comment by iamsamirzon** [comment]
This item was to perform CRUD operations on  Keys/Certificates, Trust Store, Trust Policy. But for RC-1 we are taking a simpler approach and hence proposing we move this item beyond RC-1.  

Making a decision in meeting on 5/19/2022.

**Comment by priteshbandi** [comment]
* https://github.com/notaryproject/roadmap/issues/39

**Comment by vaninrao10** [comment]
CLI commands for configuring keys and certificate is implemented in rc.1. Keep [https://github.com/notaryproject/roadmap/issues/39] open for "Trust Policy CLI commands" for later release.
