### ISSUE TITLE
[User Story] - notation trust store experience via Notation cli commands

### ISSUE THREAD

**Issue by iamsamirzon** [notaryproject/roadmap#38]
As a user, I want to configure trust store using the notation cli or configuration file(s) so that I can authenticate signed artifacts.

Original description:
**Summary**
**Intended Outcome**
The implementation matches with the specification.
**Additional context**
Will be revised based on spec updates in each alpha release. The first alpha release will have a baseline implementation that will continue to get revised until we get to release candidate

- [x] https://github.com/notaryproject/notation/issues/225
- [x] https://github.com/notaryproject/notation/issues/228

**Comment by iamsamirzon** [comment]
@SteveLasker , @gokarnm   - Based on the directory structure method of configuring trust store for Notation, I believe we can close  or defer this roadmap item as not needed/applicable for initial release. Let me know if you think otherwise.

**Comment by iamsamirzon** [comment]
@dtzar  - I am marking this for our "discuss" milestone, as this is not a blocking experience for RC-1.

**Comment by iamsamirzon** [comment]
@yizha1  - I think once we have the effort/scope done for the additional CLI work for trust store and trust policy, then we can make a decision of delaying or including.

**Comment by yizha1** [comment]
@iamsamirzon  as discussed in the community call, could you split this user story to two, one for trust store and one for trust policy.

**Comment by iamsamirzon** [comment]
@iamsamirzon  modified this issue for just the trust store requirement,. Trust policy will be handled by #39 ( as suggested by @yizha1 )

**Comment by iamsamirzon** [comment]
During the 9/19 meeting, feedback was directly given for this CLI command proposal from Yi. https://hackmd.io/V-0Nhl4mT7Sa0NPiCVgMlQ?both

**Comment by yizha1** [comment]
PR created for Trust store CLI spec https://github.com/notaryproject/notation/pull/361

**Comment by yizha1** [comment]
Close as completed.
