### ISSUE TITLE
[User Story] - Notation Sign Experience

### ISSUE THREAD

**Issue by iamsamirzon** [notaryproject/roadmap#40]
**Summary**
 As a user signing with Notation CLI, I have  well defined command structure and implementation to sign. I can use Notation CLI to sign artifacts. The CLI command along with its "sub attributes" is well defined and documented.

**Intended Outcome**
The implementation matches the specification

**Additional context**

- [x] https://github.com/notaryproject/notation/issues/91 
- [x] https://github.com/notaryproject/notation/issues/215

**Comment by dtzar** [comment]
This is replaced by https://github.com/notaryproject/notation/issues/227

**Comment by iamsamirzon** [comment]
@dtzar - I suggest we reopen it and close it after the actual work is completed in Notation.

**Comment by dtzar** [comment]
Reopening until we potentially land on something other than roadmap.
https://github.com/notaryproject/notaryproject/issues/104

**Comment by yizha1** [comment]
Close as completed.
