### ISSUE TITLE
CLI Local Storage Spec

### ISSUE THREAD

**Issue by iamsamirzon** [notaryproject/roadmap#43]
**Summary**
Define how Notation will work with local ( host) storage
**Intended Outcome**
Notation CLI implementations allows for this use case
The specfication PR is merged
**Additional context**
Will update based on finalized design/spec in prior version of alpha release
The implementation work is in https://github.com/notaryproject/roadmap/issues/46
Specification work will be in https://github.com/notaryproject/roadmap/issues/43

**Comment by iamsamirzon** [comment]
Revisit later.

**Comment by dtzar** [comment]
Replacing this with https://github.com/notaryproject/notaryproject/issues/182
