### ISSUE TITLE
E2E Automation Testing for CLI commands

### ISSUE THREAD

**Issue by iamsamirzon** [notaryproject/roadmap#47]
**Summary** 
Automated Test Cases to be executed before every release
**Intended Outcome** 
A test suite is created over time and added itertively over the lifetime of this project development
**Additional context**
Will update based on finalized design/spec in prior version of alpha release

**Comment by FeynmanZhou** [comment]
Hi @iamsamirzon ,

I assume this issue is requesting E2E testing for Notation CLI. We [investigated the Golang-native E2E test framework in ORAS CLI](https://github.com/oras-project/oras/discussions/485) and finally chose ginkgo+gomega. 

We can reuse the same E2E test framework and solution in Notation CLI. How about transferring this issue to the Notation repo?

**Comment by iamsamirzon** [comment]
@FeynmanZhou - Yes, this is for the end to end testing of Notation CLI workflows. I suggest you leave this issue as is here, in the roadmap repo, but covert it into a "User Story" format. And then link it to the new issue/PR you create in "notation" to actually implement it. As I think, this issue here will become an epic with multiple end to end test cases implemented inside "notation" repo that will complete this "roadmap" item

**Comment by dtzar** [comment]
We would have the user story here, but the actual work items in notation repo.

**Comment by dtzar** [comment]
Per the community call today, it would be good to have minimal E2E test coverage for RC.1 - such as for sign and verify workflow - and expand on this after.

**Comment by JeyJeyGao** [comment]
I will work on this task.

**Comment by yizha1** [comment]
The E2E testing work is on hold for two reasons:
- Prioritize the refactoring work
- The framework itself needs to be improved, we can leverage the ongoing work in ORAS project later.

@dtzar @toddysm @vaninrao10 @shizhMSFT

**Comment by yizha1** [comment]
updated to rc.2 per discussion.

**Comment by yizha1** [comment]
Close as released in rc.2
