### ISSUE TITLE
[User Story] Support Notation with Distribution 1.0 Spec Based Registries (Interop)

### ISSUE THREAD

**Issue by iamsamirzon** [notaryproject/roadmap#48]
As a user I want to sign and verify images stored in OCI 1.0 based registries that have not yet implemented the "referrers API"

**Summary** 
     Fallback support for existing registries which haven't yet implemented the OCI artifact specification

**Intended Outcome**
   The specification PR is merged

**Additional context**
1. This  will require client tooling work for Notation.
2. This should not require any work on the Registry side.
3. Related to issue https://github.com/notaryproject/notaryproject/issues/112 
4. Related to issue https://github.com/notaryproject/notaryproject/issues/214

**Comment by SteveLasker** [comment]
Requirements being captured here: https://hackmd.io/dwf12_dlTHacUDKFyGsOqw

**Comment by iamsamirzon** [comment]
@SteveLasker  - Is this needed for RC-2 or beyond?

**Comment by yizha1** [comment]
Maybe this roadmap issue should be changed to "OCI artifact manifest" support

**Comment by iamsamirzon** [comment]
Closing this item, as the work for OCI 1.1 based registries is already completed after we brought in the latest ORAS-go client into notation that supports OCI 1.1 based registry candidate spec. The support for "Fallback" will come in via this open issue - https://github.com/notaryproject/notation/issues/444 

cc: @vaninrao10 , @SteveLasker , @yizha1 , @dtzar

**Comment by iamsamirzon** [comment]
Reopening this roadmap item as spec needs to be updated to reflect that Notary v2 will support OCI 1.0 and OCI 1.1 based registries both. This decision is based on the agreement in NV2 community call on 12/5/2022.

cc: @vaninrao10 , @toddysm , @SteveLasker , @sajayantony , @priteshbandi

**Comment by yizha1** [comment]
IMO, the scope is the same as this one https://github.com/notaryproject/notation/issues/444

**Comment by iamsamirzon** [comment]
Yes, @yizha1 . The scope is the same. This issue #48 in the roadmap repo will be closed once we complete the work in https://github.com/notaryproject/notation/issues/444 and another other item we identify along the way.

**Comment by yizha1** [comment]
Closed as released in rc.2
