### ISSUE TITLE
[User Story] - Support COSE as signing envelope

### ISSUE THREAD

**Issue by iamsamirzon** [notaryproject/roadmap#7]
**Summary**
As a user, I would like to see Notary v2 support [CBOR Object Signing and Encryption (COSE)](https://datatracker.ietf.org/doc/html/rfc8152) as signing envelope.

**Intended Outcome**
The essential [Signing and verification workflow](https://github.com/notaryproject/notaryproject/blob/main/signing-and-verification-workflow.md) should work for COSE as signing envelope

**Additional context**

- COSE spec is tracked at https://github.com/notaryproject/notaryproject/issues/117 
- notation COSE impelmentation is tracked at https://github.com/notaryproject/notation/issues/163

**Comment by iamsamirzon** [comment]
@yizha1  - I am marking COSE support as a "discuss" milestone item. We anyways have this other COSE item (https://github.com/notaryproject/notaryproject/issues/117) in "discuss" milestone, lets track this roadmap item there until the maintainers can agree on which release it should come in.

**Comment by yizha1** [comment]
@iamsamirzon  As discussed in today's meeting, how about changing the milestone from "Discuss" to "rc.1" for this user story?

**Comment by yizha1** [comment]
Change milestone to rc.1 according to the discussion on community call on Aug 29. The COSE implementation is done in a separate cose branch and is now being merged back into the main branch.

**Comment by yizha1** [comment]
The work done in cose branch will be merged to main by several PRs

**Comment by yizha1** [comment]
Close as completed.
