### ISSUE TITLE
[Spec] Notation sign/verify Offline/Local artifacts

### ISSUE THREAD

**Issue by yizha1** [notaryproject/roadmap#73]
### Summary
Create specifications for `Notation sign/verify Offline/Local artifacts`

### Intended Outcome
The specification PRs are reviewed, merged, and stored under https://github.com/notaryproject/notaryproject/tree/main/specs

### Additional context
This is not required to be completed in rc.2

**Comment by iamsamirzon** [comment]
@toddysm , @vaninrao10 , @FeynmanZhou , @yizha1 - Based on RC-2 discussion in today's Notary v2 meeting, I am pushing back this item from the RC-2 roadmap into the backlog.

**Comment by yizha1** [comment]
Update the milestone to rc-3 based on the [discussion](https://hackmd.io/WVFhrhvYSFutJpnY6JTDuQ?view#RC-3-Release-Items---March-30th-2023-Can-be-called-GA-----Gives-5-weeks-after-rc-2-release).

**Comment by yizha1** [comment]
Spec is done for sign oci layout. new issues will be created under notation repo for other scenarios.
