### ISSUE TITLE
[User Story] notation inspect signatures

### ISSUE THREAD

**Issue by SteveLasker** [notaryproject/roadmap#74]
As a user, I want to inspect signatures so that I can make a more informed decision to trust the signer and make it easy to start trusting them.

Notary v2 does not support Trust On First Use (TOFU), and only trusts artifacts that have been configured with trusted keys, which means users need a way to find the public key to place within their trust store.

## Scenario:

A user found a signed image in a registry they wish to use. The image may have been promoted to a private registry, decoupling the original location. 
How do they find and download the public key to configure their trust policy? 
The signature(s) provide the identity(s) of the entity(s) that signed the artifact. How does the user discover the info about the signers?

## Proposal

A proposed API: `notation inspect registry.wabbit-networks.io/net-monitor:v1` would extract information _about_ the signing key, such as the location of the company that signed it, enabling the user to locate the public root key.

The user could then download the public key from the location and configure their trust policy. 

The model here is not TOFU, rather a discoverability model for the user to make an educated decision about the identity of an artifact, and decide if they choose to trust them.

## Implementation items to complete

- [ ] notaryproject/notation#213
- [ ] https://github.com/notaryproject/notation/issues/219

**Comment by iamsamirzon** [comment]
As a user of the signature, I will want Inspect command to display any other aspects encoded in the signature, such as (Common name of the signing identity, trust anchor, any metadata that the signer provided during signing). Essentially a human readable format of the signature.

**Comment by yizha1** [comment]
Closed as released in rc.2
