### ISSUE TITLE
Create org-wide repository for governance documents and templates

### ISSUE THREAD

**Issue by toddysm** [notaryproject/roadmap#77]
As a result of the discussion in CNCF TOC regarding the status of the Notary project, we discussed in a few of the Notary meetings to increase the visibility of the governance documents as well as to update the list of maintainers. With this issue, I would like to propose to the community to move the governance documents from their current location (under the `notaryproject/notary` repo) to a standard `.github` repo as per the following GitHub documentation https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/creating-a-default-community-health-file

The goal for the new repo will be to store the following governance documents:
- [GOVERNANCE.md](https://github.com/notaryproject/notary/blob/master/GOVERNANCE.md)
- [CODE_OF_CONDUCT.md](https://github.com/notaryproject/notary/blob/master/CODE_OF_CONDUCT.md)
- [CONTRIBUTING.md](https://github.com/notaryproject/notary/blob/master/CONTRIBUTING.md)

As well as to create standard issue and PR templates as in https://github.com/notaryproject/notation/tree/main/.github/ISSUE_TEMPLATE that can be leveraged for all repos under the organization. 

This proposal is to just migrate the documents to a central place. For updating the governance documents, adding new documents like SECURITY.md, or updating maintainers, we should file separate issue.

Filing in this repository as the most generic repository under the organization.

**Comment by toddysm** [comment]
Please sign off in a comment if you agree or add your comments.

**Comment by SteveLasker** [comment]
👍

**Comment by iamsamirzon** [comment]
LGTM

**Comment by priteshbandi** [comment]
LGTM 👍

**Comment by FeynmanZhou** [comment]
LGTM

**Comment by vaninrao10** [comment]
LGTM

**Comment by vaninrao10** [comment]
LGTM

**Comment by toddysm** [comment]
Based on the responses above as well as the discussion in the Notary meeting from Jan 30th 2023 (https://hackmd.io/_vrqBGAOSUC_VWvFzWruZw) the decision is to proceed with this proposal and create `.github` repo under the project to use for governance documents. I will go ahead and start this process and close the issue when it is done.

**Comment by toddysm** [comment]
Folks, I have created the repository https://github.com/notaryproject/.github and closing this issue as a result. Please look for some PRs in the new repository for approvals.
